version: 2.1
orbs:
  docker: circleci/docker@1.7.0
  kubernetes: circleci/kubernetes@1.3.1
jobs:
  test-unit:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Unit Tests
          command: make test-unit
  test-integration:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Integration Tests
          command: make test-integration
  test-functional:
    docker:
      - image: cimg/go:1.20
    working_directory: ~/repo
    steps:
      - checkout
      - run: make run
      - run:
          name: Functional Tests
          command: make docker-test-functional
  deploy:
    docker:
      - image: cimg/base:stable
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: Set version
          command: |
            make print-version | cat > version.txt
            make print-branch | cat > branch.txt
            make print-rev | cat > rev.txt
            make print-build-user | cat > build-user.txt
      - kubernetes/install-kubectl
      - kubernetes/install-kubeconfig:
          kubeconfig: KUBECONFIG_DATA
      - setup_remote_docker:
          docker_layer_caching: false
      - run: docker login -u i0nw -p $(echo ${DOCKERHUB_PASSWORD})
      - run:  docker build . --build-arg DOCKER_ARG_VERSION=$(cat version.txt) --build-arg DOCKER_ARG_REV=$(cat rev.txt) --build-arg DOCKER_ARG_BRANCH=$(cat branch.txt) --build-arg DOCKER_ARG_BUILD_USER=$(cat build-user.txt) -t i0nw/gokv:latest
      - run: docker tag i0nw/gokv:latest i0nw/gokv:$(cat version.txt)
      - run: |
          docker push i0nw/gokv:latest
          docker push i0nw/gokv:$(cat version.txt)
      - kubernetes/update-container-image:
          container-image-updates: "app=i0nw/gokv:$(cat version.txt)"
          get-rollout-status: true
          resource-name: deployment/gokv
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - test-unit:
          filters:
            branches:
              only: main
      - test-integration:
          requires:
            - test-unit
      - test-functional:
          requires:
            - test-integration
      - deploy:
          requires:
            - test-functional
